### ISSUE TITLE
CSS parsing issue

### ISSUE THREAD

**Issue by tosbaha** [mattt/Ono#29]
CSS selector is not working for UPS web site with 
1ZA829420304772945 as tracking code. I put the result on http://pastebin.com/7wj6AMTm I tried o use ```table.dataTable``` and ```.dataTable``` selectors. Both of them are returning nil. However ```.//*/table[@class='dataTable']``` XPath is working correctly.

**Comment by mattt** [comment]
Please submit a PR with a failing test. I might be able to fix it with that.
