### ISSUE TITLE
XML containing non-printable ASCII characters parsing issue

### ISSUE THREAD

**Issue by aetern** [mattt/Ono#42]
If there are some non-printable ASCII characters inside a `CDATA` section in a XML document, the document object will miss some content.

Suppose I get this from the server.

``` xml
<blog>
<title><![CDATA[Example]]></title>
<commentCount>0</commentCount>
<body>
<![CDATA[
    XXX
    This  line  contains non-printable ascii characters.
    XXX
]]>
</body>
<author><![CDATA[Author]]></author>
<pubDate>2015-07-21 20:24:36</pubDate>
</blog>
```

The response ONOXMLDocument object will be

``` xml
<blog>
<title><![CDATA[Example]]></title>
<commentCount>0</commentCount>
<body>
 line  contains</body></blog>
```

This case happens only when non-printable characters are inside a `CDATA` section.

**Comment by zhuhejin** [comment]
use like [[[aElement childrenWithTag:@"text"] firstObject] stringValue]   can fix this bug

**Comment by mattt** [comment]
Thanks for the suggested fix, @zhuhejin! 

@aetern: Please let me know if you are still having an issue here, and I'd be happy to take another look.
