### ISSUE TITLE
WatchOS

### ISSUE THREAD

**Issue by fousa** [mattt/Ono#43]
Hi Mattt,

Any change you can support watchOS 2?

Cocoapods updated their implementation, more information can be found [here](http://blog.cocoapods.org/CocoaPods-0.38/). I can take a look later if you want.

**Comment by cezheng** [comment]
Hi @fousa 

Mattt seems to be too busy to login github to look at these PRs and issues for the recent few months, and I have just ported Ono to Swift with some redesign following common swift convention, as well as some bug fixes. All tests in Ono passed.

If you happen to be using Ono on a Swift project, maybe you can try it.

https://github.com/cezheng/Fuzi

Of course, watchOS target is also included.

I will be actively maintaining the library so I'll be glad to have your feedback if you would give it a try ;)

**Comment by mattt** [comment]
Apologies for not responding sooner, @fousa. As of fe2cc875d2e5, Ono now has watchOS support.
