### ISSUE TITLE
not work with ![CDATA[xxxx]]

### ISSUE THREAD

**Issue by zhuhejin** [mattt/Ono#46]
Ono does not work with ![CDATA[xxxx]]

**Comment by zhuhejin** [comment]
use like [[[aElement childrenWithTag:@"text"] firstObject] stringValue]   can fix this bug

**Comment by cezheng** [comment]
@zhuhejin Would you mind sharing an example(code & relevant XML)?

**Comment by zhuhejin** [comment]
i had fixed this problem

self. commentText =[[aElement firstChildWithTag:@"text"] stringValue];   //return nil;


self.commentText=[[[aElement childrenWithTag:@"text"] firstObject] stringValue]; // return correct;

my XML  

<item>
        <created_at>2015-10-27 08:47</created_at>
        <id>F20151027d084707oeLUPihbuuWwyFmV</id>
        <text>
            <![CDATA[早上好]]>
        </text>
        <recommend>0</recommend>
        <commentcount>0</commentcount>
        <user>
            <userid>45</userid>
            <name>李瑞华</name>
            <profile_image_url>
                <![CDATA[http://demo.api.meetmesns.com:6011/Upload/photo/20150930095809KmjYiOStp@2x.png]]>
            </profile_image_url>
            <company>台湾清华大学经济管理学院管理</company>
            <title>教授</title>
        </user>
    </item>

thanks for your Ono

**Comment by gcox** [comment]
@cezheng Here's an example tag whose stringValue returns @"" for me. @zhuhejin's suggested workaround does not work for this case and also returns @"".

```
<link>
    <![CDATA[http://www.earwolf.com/show/comedy-bang-bang/]]>
</link>
```
Other tags containing text wrapped in <![CDATA[xxxx]]> parses without a problem.

**Comment by cezheng** [comment]
@gcox I found that if you read the document as HTML, then CDATA won't be recognized, you have to treat it as an XML document

**Comment by gcox** [comment]
@cezheng I'm not sure what you mean, the NSData object I'm using to load the ONXMLDocument is downloaded from a server returning application/rss+xml. Is ```-[ONXMLElement firstChildWithTag:]``` meant to be used against HTML documents only?

I did find that grabbing the ONOXMLElement from the result of ```-[ONOXMLDocument XPath:]``` got me an ONXMLElement object that returns the correct stringValue.

**Comment by gcox** [comment]
@cezheng I figured out the problem...it's my fault.  There was another 'link' tag with a namespace, I incorrectly assumed ```firstChildWithTag:@"link"``` would consider ```<atom:link``` to be a match.

**Comment by mattt** [comment]
Apologies for not responding to this sooner, @zhuhejin. If this is still an issue for you, please let me know, and I'll reopen. Thanks!
