### ISSUE TITLE
CSS selector does not work for some queries

### ISSUE THREAD

**Issue by youngcha101** [mattt/Ono#47]
Thanks for the very helpful library!
While using this with HTML, I found some CSS selector queries don't work. For example, when I tried to find elements under a specific element with a query like "#price .a-color-price", it generates the error below:

XPath error : Invalid expression
.//_[@id = 'price']/descendant::_[@id = 'a-col']*[contains(concat(' ',normalize-space(@class),' '),' a-color-price ')]

Can you please fix this error if I'm not using CSS selector in a wrong way?

**Comment by cezheng** [comment]
@youngcha101 Ono does have this bug and I once made a Pull Request to fix this.
https://github.com/mattt/Ono/pull/41/files

But mattt is not active on github for 5 months already so this won't be merged.

If you are using Objective-C then modifying the source code yourself as I did in the PR should fix the problem. If you happen to be using Swift, you could try my Swift port of Ono: https://github.com/cezheng/Fuzi which has this bug fixed.

**Comment by youngcha101** [comment]
It works:) Thanks!

**Comment by mattt** [comment]
Apologies for not responding sooner, @youngcha101. I have now cherry-picked the bug fix from @cezheng's PR #41.
