### ISSUE TITLE
Build error in XCode7.1

### ISSUE THREAD

**Issue by zhangyicococo** [mattt/Ono#48]
Tests/ONOHTMLTests.m file

```Swift
- (void)testRootElementChildren {
    NSArray *children = [self.document.rootElement children];
    XCTAssertNotNil(children, @"children should not be nil");
    XCTAssertTrue([children count] == 2, @"root element has more than two children");
    XCTAssertEqualObjects([[children firstObject] tag], @"head", @"head not first child of html");
    XCTAssertEqualObjects([[children lastObject] tag], @"body", @"body not last child of html");
}
```

The last two line of that method occurs following error : 

"Multiple methods named 'tag' found with mismatched result, parameter type or attributes..."

Is there any way to fix this? Please help me.
Thanks.

**Comment by cezheng** [comment]
This is only a test method and should not affect the framework build

**Comment by zhangyicococo** [comment]
Yeah I used Carthage to include this framework on my project and it fails due to that error.

**Comment by cezheng** [comment]
@zhangyicococo mattt is not maintaining this repo so it won't be fixed. You may create your own fork and fix it in this way: https://github.com/mattt/Ono/pull/41/files#diff-0b31a3a8adc178ba70e7b588f6e6dcf7L54

**Comment by cezheng** [comment]
@zhangyicococo If you happen to be using Swift, then you may try this repo: https://github.com/cezheng/Fuzi

**Comment by zhangyicococo** [comment]
Ok thanks, I will close the issue.
