### ISSUE TITLE
Memory leak in firstChildWithXPath/enumerateElementsWithXPath when no element found

### ISSUE THREAD

**Issue by occultknight** [mattt/Ono#49]
Fix by adding "xmlXPathFreeObject(XPath)" under line 345 of ONOXMLDocument.m

**Comment by krzysztofkluskamiquido** [comment]
any update on this ? Proposed fix is working correctly. 

Would be nice to release new version so people don't have to fork this pod :).

**Comment by cezheng** [comment]
This repo seems to be abandoned. Objective-C projects will have to fix it yourself. Swift projects may give this a try: https://github.com/cezheng/Fuzi

It is based on a Swift port of Ono including several bug fixes including this one.

**Comment by mattt** [comment]
Apologies for not responding sooner, @occultknight. This is now fixed by 3147668d48fcb3214ff1b75c91c9a0fc454116ad.
