### ISSUE TITLE
warnings when building with -Weverything

### ISSUE THREAD

**Issue by core-code** [mattt/Ono#71]
all of these individual warnings come up when compiling ONOXMLDocument.m with -Weverything

-Wshadow
-Wsign-conversion
-Wfloat-conversion
-Wconversion
-Wnullable-to-nonnull-conversion
-Wcast-qual

**Comment by mattt** [comment]
Thanks for bringing this to my attention, @core-code. I just pushed version 2.1.0, which should resolve all of the warnings you were seeing. Please let me know if there are any stray ones that I missed, and I'll be happy to take another look.

**Comment by core-code** [comment]
awesome thanks.

just a minor heads-up, i think the #pragma clang diagnostic push at the bottom of ONOXMLDocument.h should read "pop" not "push"

**Comment by mattt** [comment]
😓 Yikes. That's no good. I'm surprised the compiler didn't warn about that.

I fixed this with 39ece84cc0035afbea20682631fe8a6d11e32692, and fixed a related issue I found in Xcode 9.4.1 with 33b38b8c9eeb5387477a130b7c0d3a511d13e592. These are pushed with 2.1.1.
